Download large data files before build
systemsomicslab/MsdialWorkbench pull request #18
Opened 2023-02-02 10:28 UTC by kozo2

2023-02-03 03:11 UTC, YukiMatsuzawa commented on src/MSDIAL4/MsDial/MSDIAL.csproj
> +			Condition="Exists('$(OutputPath)\README.md')" />
README.md is remains.

Since there can be several types of lbm files and there must be only one lbm file in a folder, it may be better to use pattern matching of extensions to determine this.

[This site](https://social.msdn.microsoft.com/Forums/vstudio/en-US/21773acc-4d0f-44bb-96e2-d933fabc833f/how-to-use-wildcards-with-the-exists-condition?forum=msbuild) may be useful for matching by extension.

2023-02-03 03:12 UTC, YukiMatsuzawa commented on src/MSDIAL5/MsdialGuiApp/MsdialGuiApp.csproj
> +		<Lbm2Url>http://prime.psc.riken.jp/compms/msdial/download/lipidblast/LipidMsmsBinaryDB-VS68-AritaM.lbm2</Lbm2Url>
I don't think we currently distributed the lbm file for version 5.

2023-02-03 03:13 UTC, YukiMatsuzawa commented on src/MSDIAL5/MsdialGuiApp/MsdialGuiApp.csproj
> +			Condition="Exists('$(OutputPath)\README.md')" />
Same as MSDIAL.csproj.

2023-02-15 08:49 UTC, kozo2 commented on src/MSDIAL4/MsDial/MSDIAL.csproj
> +			Condition="Exists('$(OutputPath)\README.md')" />
I updated to follow the comment in https://github.com/systemsomicslab/MsdialWorkbench/commit/53e610aba31004e45dd66f05f1736ea6e13f4102

2023-02-15 08:49 UTC, kozo2 commented on src/MSDIAL5/MsdialGuiApp/MsdialGuiApp.csproj
> +		<Lbm2Url>http://prime.psc.riken.jp/compms/msdial/download/lipidblast/LipidMsmsBinaryDB-VS68-AritaM.lbm2</Lbm2Url>
I updated to follow the comment in https://github.com/systemsomicslab/MsdialWorkbench/commit/53e610aba31004e45dd66f05f1736ea6e13f4102

2023-02-15 08:50 UTC, kozo2 commented on src/MSDIAL5/MsdialGuiApp/MsdialGuiApp.csproj
> +			Condition="Exists('$(OutputPath)\README.md')" />
I updated to follow the comment in https://github.com/systemsomicslab/MsdialWorkbench/commit/53e610aba31004e45dd66f05f1736ea6e13f4102

2023-02-15 11:34 UTC, YukiMatsuzawa requested changes

2023-02-15 11:34 UTC, YukiMatsuzawa commented on src/MSDIAL5/MsdialGuiApp/MsdialGuiApp.csproj
> +			Condition="!Exists('$(OutputPath)\*.lvm*')" />
```suggestion
			Condition="!Exists('$(OutputPath)\*.lbm*')" />
```

2023-02-15 11:37 UTC, merged